// $(document).ready(function(){
// 	$(".image").mouseover(
// 		function(){
// 			$(".filter-hover").css("opacity","0.6");
// 			$(".filter-hover-text").css("opacity","1");
// 			console.log("yes");
// 		})
// 	.mouseout(function(){
// 		$(".filter-hover").css("opacity","0");
// 		$(".filter-hover-text").css("opacity","0");
// 	})
// })